### ISSUE TITLE
in table - side by side example

### ISSUE THREAD

**Issue by leonix2015** [PixelsCommander/Propeller#16]
I am trying to do this: http://fpa-voices.com/wheel3/example/leo.html
the problem is that the wheel on the right behaves differently...

**Comment by PixelsCommander** [comment]
It is not because of second or first it is because you use iframe and
coordinates systems inside of iframe and on the screen are different. The
first propeller stands on 0,0 coordinates which makes no difference between
coordinate inside of iframe and on the page globally. But second one have
some shift which creates some problems.

Moving propellers out of iframes will solve your issue.

2015-11-02 18:27 GMT+01:00 leonix2015 <notifications@github.com>:
